### 3. Create a dictionary where the keys are multiples of 3 among the first 100 natural numbers and each value is the cube of the key.

In [1]:
# Multiples of 3 among the first 100 natural numbers
dict_3 = {x: x**3 for x in range(1, 101) if x % 3 == 0}
print(dict_3)

{3: 27, 6: 216, 9: 729, 12: 1728, 15: 3375, 18: 5832, 21: 9261, 24: 13824, 27: 19683, 30: 27000, 33: 35937, 36: 46656, 39: 59319, 42: 74088, 45: 91125, 48: 110592, 51: 132651, 54: 157464, 57: 185193, 60: 216000, 63: 250047, 66: 287496, 69: 328509, 72: 373248, 75: 421875, 78: 474552, 81: 531441, 84: 592704, 87: 658503, 90: 729000, 93: 804357, 96: 884736, 99: 970299}


### 4. Write a code in one line to print following results:

i/p: `List 1=['a', 'b', 'c']`, `list2=['d', 'e', 'f']`<br>
o/p: `['ad', 'ae', 'af', 'bd', 'be', 'bf', 'cd', 'ce', 'cf']`

i/p: `List 1=['a', 'c', 'd', 'b']`<br>
o/p: `{'A': 'aaa', 'C': 'ccc', 'B': 'bbb', 'D': 'ddd'}`

In [ ]:
print([x + y for x in ['a', 'b', 'c'] for y in ['d', 'e', 'f']])

print({k.upper(): k*3 for k in ['a', 'c', 'd', 'b']})

['ad', 'ae', 'af', 'bd', 'be', 'bf', 'cd', 'ce', 'cf']
{'A': 'aaa', 'C': 'ccc', 'D': 'ddd', 'B': 'bbb'}


### 5. Write a python code to Make the following 4x7 array called nola that starts with 1 and steps by 2. However, note that the first element in each row is always 4 more than the last element in the previous row.

```text
nola= [[ 1,  3,  5,  7,  9, 11, 13],
       [17, 19, 21, 23, 25, 27, 29],
       [33, 35, 37, 39, 41, 43, 45],
       [49, 51, 53, 55, 57, 59, 61]]
```

In [ ]:
import numpy as np

nola = np.array([np.arange(1, 15, 2) + 16*i for i in range(4)]) # np.arrange used to create 1d arrays with evenly spaced values
print(nola)

[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]


### 6. Define a roux array as a 1-D array such that, when it's reversed, it represents the sequence of square numbers 1,4,9,16,... with 0s Interwoven between them.

In [23]:
import numpy as np

def create_roux_array(n):
    num_squares = (n + 1) // 2
    squares = [i**2 for i in range(1, num_squares + 1)]
    
    seq = []
    for sq in squares:
        seq.append(sq)
        seq.append(0)
    
    seq = seq[:n] #trimming to n
    
    roux = seq[::-1]
    return np.array(roux)

print("roux array of length 8: ")
print(create_roux_array(8))

roux array of length 8: 
[ 0 16  0  9  0  4  0  1]


In [6]:
import numpy as np

### 7. Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

In [26]:
array1 = np.array([0,10,20,40,60])
array2 = np.array([0,40])

print("Array1:", array1)
print("Array2:", array2)
print(np.isin(array1, array2))

Array1: [ 0 10 20 40 60]
Array2: [ 0 40]
[ True False False  True False]


### 8. Write a NumPy program to get the unique elements of an array

In [27]:
import numpy as np

arr1 = np.array([10, 10, 20, 20, 30, 30])
print(arr1)
print("Unique elements: ", np.unique(arr1))

arr2 = np.array([[1, 1], [2, 3]])
print("Original array: ")
print(arr2)
print("Unique elements: ", np.unique(arr2))

[10 10 20 20 30 30]
Unique elements:  [10 20 30]
Original array: 
[[1 1]
 [2 3]]
Unique elements:  [1 2 3]


### 9. Write a NumPy program to sort an along the first, last axis of an array.

In [ ]:
import numpy as np

array1 = np.array([[4, 6], [2, 1]])
print("Original array:")
print(array1)

print("Sort along the first axis:")
print(np.sort(array1, axis=0)) # column sort

print("Sort along the last axis:")
print(np.sort(array1, axis=1)) # row sort

Original array:
[[4 6]
 [2 1]]
Sort along the first axis:
[[2 1]
 [4 6]]
Sort along the last axis:
[[4 6]
 [1 2]]


### 10. Write a program to count the occurrence of a specified item in a given NumPy array. And write a NumPy program to remove nan values from a given array.

In [ ]:
import numpy as np

arr_count = np.array([10, 20, 20, 20, 20, 0, 20, 30, 30, 30, 0, 0, 20, 20, 0])
print(arr_count)
unique, counts = np.unique(arr_count, return_counts=True)
print("Occurrences:", counts[np.argsort(unique)])



Original array:
[10 20 20 20 20  0 20 30 30 30  0  0 20 20  0]
Occurrences: [4 1 7 3]
Original array:
[200. 300.  nan  nan  nan 700.]
After removing nan values: [200. 300. 700.]


### 11. Write a NumPy program to calculate percentiles for a sequence or single-dimensional NumPy array.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("50th percentile:", np.percentile(arr, 50))
print("40th percentile:", np.percentile(arr, 40))
print("90th percentile:", np.percentile(arr, 90))

50th percentile (median): 3.0
40th percentile: 2.6
90th percentile: 4.6


### 12. Write a NumPy program to find indices of elements equal to zero in a NumPy array.

In [ ]:
import numpy as np

arr_zero = np.array([1, 0, 2, 0, 3, 0, 4, 5, 6, 7, 8])
print(arr_zero)
print("Indices of zero:", np.where(arr_zero == 0)[0]) # returns (array([1, 3]),) and [0] extracts first index of it

[1 0 2 0 3 0 4 5 6 7 8]
Indices of zero: [1 3 5]


### 13. Write a NumPy program to get the indices of the sorted elements of a given array.

In [31]:
import numpy as np

arr_sort = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print(arr_sort)
print("Indices of sorted elements:", np.argsort(arr_sort))

[1023 5202 6230 1671 1682 5241 4532]
Indices of sorted elements: [0 3 4 6 1 5 2]


### 14. Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice).

In [33]:
import numpy as np

arr_part = np.array([70, 50, 20, 30, -11, 60, 50, 40])
print(arr_part)
print("After partitioning on 4 the position:", np.partition(arr_part, 4))

[ 70  50  20  30 -11  60  50  40]
After partitioning on 4 the position: [-11  20  30  40  50  50  60  70]


### 15. Compute the euclidean distance between two arrays a and b.

In [18]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
distance = np.linalg.norm(a - b)
print("Euclidean distance is:", round(distance, 4))

Euclidean distance is: 6.7082


### 16. Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

In [19]:
import numpy as np

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
peaks = np.where((a[1:-1] > a[:-2]) & (a[1:-1] > a[2:]))[0] + 1
print(peaks)

[2 5]


### 17. Find the index of nth repetition of number i.

In [20]:
import numpy as np

arr_rep = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5
i = 1
indices = np.where(arr_rep == i)[0]
if len(indices) >= n:
    print(indices[n-1])
else:
    print("Not found")

8
